version: '3.5'
services:
  demo:
    build: .
    container_name:
      deploy-python-demo
    ports:
      - 8000:8000
    command: sh -c "python3 manage.py runserver [::]:8000"
    volumes: 
      - ./settings.py:/django-helloworld/helloworld/settings.py
    restart: on-failure 
  nginx:
    image:
      nginx:mainline
    ports:
      - 80:80
    volumes:
      - ./deploy-python.conf:/etc/nginx/conf.d/deploy-python.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    container_name:
      deploy-python-nginx
    depends_on:
      - demo
    restart: on-failure 